// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feirafacil.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the FeiraFacil module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Cadastro_Despensa_CreateBuilder(
		feirafacil.proxies.Cadastro _cadastro
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("FeiraFacil.ACT_Cadastro_Despensa_Create");
		builder = builder.withParam("Cadastro", _cadastro);
		return builder;
	}

	public static void aCT_Cadastro_Despensa_Create(
		IContext context,
		feirafacil.proxies.Cadastro _cadastro
	)
	{
		aCT_Cadastro_Despensa_CreateBuilder(
				_cadastro
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_PDF_GenerateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("FeiraFacil.ACT_PDF_Generate");
		return builder;
	}

	public static void aCT_PDF_Generate(IContext context)
	{
		aCT_PDF_GenerateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dOC_PDF_OpenPageBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("FeiraFacil.DOC_PDF_OpenPage");
		return builder;
	}

	public static void dOC_PDF_OpenPage(IContext context)
	{
		dOC_PDF_OpenPageBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_Data_CalculateBuilder(
		feirafacil.proxies.Lista _lista
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("FeiraFacil.MF_Data_Calculate");
		builder = builder.withParam("Lista", _lista);
		return builder;
	}

	public static java.lang.String mF_Data_Calculate(
		IContext context,
		feirafacil.proxies.Lista _lista
	)
	{
		Object result = mF_Data_CalculateBuilder(
				_lista
			)
			.execute(context);
		return (java.lang.String) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_Despensa_UpdateBuilder(
		feirafacil.proxies.Despensa _despensa
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("FeiraFacil.MF_Despensa_Update");
		builder = builder.withParam("Despensa", _despensa);
		return builder;
	}

	public static void mF_Despensa_Update(
		IContext context,
		feirafacil.proxies.Despensa _despensa
	)
	{
		mF_Despensa_UpdateBuilder(
				_despensa
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_DashboardGraficoPizza_CalculateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("FeiraFacil.SUB_DashboardGraficoPizza_Calculate");
		return builder;
	}

	public static java.util.List<feirafacil.proxies.DashboardGraficoPizza> sUB_DashboardGraficoPizza_Calculate(IContext context)
	{
		Object result = sUB_DashboardGraficoPizza_CalculateBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> feirafacil.proxies.DashboardGraficoPizza.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_DashboardIndicadores_CalculateBuilder(
		feirafacil.proxies.DashboardIndicadores _dashboard
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("FeiraFacil.SUB_DashboardIndicadores_Calculate");
		builder = builder.withParam("Dashboard", _dashboard);
		return builder;
	}

	public static void sUB_DashboardIndicadores_Calculate(
		IContext context,
		feirafacil.proxies.DashboardIndicadores _dashboard
	)
	{
		sUB_DashboardIndicadores_CalculateBuilder(
				_dashboard
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Historico_CreateBuilder(
		feirafacil.proxies.Lista _lista
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("FeiraFacil.SUB_Historico_Create");
		builder = builder.withParam("Lista", _lista);
		return builder;
	}

	public static void sUB_Historico_Create(
		IContext context,
		feirafacil.proxies.Lista _lista
	)
	{
		sUB_Historico_CreateBuilder(
				_lista
			)
			.execute(context);
	}
}
