// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feirafacil.proxies;

public class DashboardIndicadores implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dashboardIndicadoresMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FeiraFacil.DashboardIndicadores";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TotalProdutos("TotalProdutos"),
		TotalCompras("TotalCompras");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DashboardIndicadores(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DashboardIndicadores(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dashboardIndicadoresMendixObject)
	{
		if (dashboardIndicadoresMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dashboardIndicadoresMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dashboardIndicadoresMendixObject = dashboardIndicadoresMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static feirafacil.proxies.DashboardIndicadores initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new feirafacil.proxies.DashboardIndicadores(context, mendixObject);
	}

	public static feirafacil.proxies.DashboardIndicadores load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return feirafacil.proxies.DashboardIndicadores.initialize(context, mendixObject);
	}

	/**
	 * @return value of TotalProdutos
	 */
	public final java.lang.Integer getTotalProdutos()
	{
		return getTotalProdutos(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalProdutos
	 */
	public final java.lang.Integer getTotalProdutos(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalProdutos.toString());
	}

	/**
	 * Set value of TotalProdutos
	 * @param totalprodutos
	 */
	public final void setTotalProdutos(java.lang.Integer totalprodutos)
	{
		setTotalProdutos(getContext(), totalprodutos);
	}

	/**
	 * Set value of TotalProdutos
	 * @param context
	 * @param totalprodutos
	 */
	public final void setTotalProdutos(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalprodutos)
	{
		getMendixObject().setValue(context, MemberNames.TotalProdutos.toString(), totalprodutos);
	}

	/**
	 * @return value of TotalCompras
	 */
	public final java.lang.Integer getTotalCompras()
	{
		return getTotalCompras(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCompras
	 */
	public final java.lang.Integer getTotalCompras(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalCompras.toString());
	}

	/**
	 * Set value of TotalCompras
	 * @param totalcompras
	 */
	public final void setTotalCompras(java.lang.Integer totalcompras)
	{
		setTotalCompras(getContext(), totalcompras);
	}

	/**
	 * Set value of TotalCompras
	 * @param context
	 * @param totalcompras
	 */
	public final void setTotalCompras(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalcompras)
	{
		getMendixObject().setValue(context, MemberNames.TotalCompras.toString(), totalcompras);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dashboardIndicadoresMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final feirafacil.proxies.DashboardIndicadores that = (feirafacil.proxies.DashboardIndicadores) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
