// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package feirafacil.proxies;

public class Despensa implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject despensaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "FeiraFacil.Despensa";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Quantidade("Quantidade"),
		QuantidadeCompra("QuantidadeCompra"),
		Despensa_Cadastro("FeiraFacil.Despensa_Cadastro");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Despensa(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Despensa(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject despensaMendixObject)
	{
		if (despensaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, despensaMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.despensaMendixObject = despensaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static feirafacil.proxies.Despensa initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new feirafacil.proxies.Despensa(context, mendixObject);
	}

	public static feirafacil.proxies.Despensa load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return feirafacil.proxies.Despensa.initialize(context, mendixObject);
	}

	public static java.util.List<feirafacil.proxies.Despensa> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> feirafacil.proxies.Despensa.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Quantidade
	 */
	public final java.lang.Integer getQuantidade()
	{
		return getQuantidade(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantidade
	 */
	public final java.lang.Integer getQuantidade(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Quantidade.toString());
	}

	/**
	 * Set value of Quantidade
	 * @param quantidade
	 */
	public final void setQuantidade(java.lang.Integer quantidade)
	{
		setQuantidade(getContext(), quantidade);
	}

	/**
	 * Set value of Quantidade
	 * @param context
	 * @param quantidade
	 */
	public final void setQuantidade(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantidade)
	{
		getMendixObject().setValue(context, MemberNames.Quantidade.toString(), quantidade);
	}

	/**
	 * @return value of QuantidadeCompra
	 */
	public final java.lang.Integer getQuantidadeCompra()
	{
		return getQuantidadeCompra(getContext());
	}

	/**
	 * @param context
	 * @return value of QuantidadeCompra
	 */
	public final java.lang.Integer getQuantidadeCompra(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.QuantidadeCompra.toString());
	}

	/**
	 * Set value of QuantidadeCompra
	 * @param quantidadecompra
	 */
	public final void setQuantidadeCompra(java.lang.Integer quantidadecompra)
	{
		setQuantidadeCompra(getContext(), quantidadecompra);
	}

	/**
	 * Set value of QuantidadeCompra
	 * @param context
	 * @param quantidadecompra
	 */
	public final void setQuantidadeCompra(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer quantidadecompra)
	{
		getMendixObject().setValue(context, MemberNames.QuantidadeCompra.toString(), quantidadecompra);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Despensa_Cadastro
	 */
	public final feirafacil.proxies.Cadastro getDespensa_Cadastro() throws com.mendix.core.CoreException
	{
		return getDespensa_Cadastro(getContext());
	}

	/**
	 * @param context
	 * @return value of Despensa_Cadastro
	 * @throws com.mendix.core.CoreException
	 */
	public final feirafacil.proxies.Cadastro getDespensa_Cadastro(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		feirafacil.proxies.Cadastro result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Despensa_Cadastro.toString());
		if (identifier != null) {
			result = feirafacil.proxies.Cadastro.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Despensa_Cadastro
	 * @param despensa_cadastro
	 */
	public final void setDespensa_Cadastro(feirafacil.proxies.Cadastro despensa_cadastro)
	{
		setDespensa_Cadastro(getContext(), despensa_cadastro);
	}

	/**
	 * Set value of Despensa_Cadastro
	 * @param context
	 * @param despensa_cadastro
	 */
	public final void setDespensa_Cadastro(com.mendix.systemwideinterfaces.core.IContext context, feirafacil.proxies.Cadastro despensa_cadastro)
	{
		if (despensa_cadastro == null) {
			getMendixObject().setValue(context, MemberNames.Despensa_Cadastro.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Despensa_Cadastro.toString(), despensa_cadastro.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return despensaMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final feirafacil.proxies.Despensa that = (feirafacil.proxies.Despensa) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
